from sqlalchemy import Column, String, Integer, TIMESTAMP, func, text, Boolean
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql.schema import ForeignKey

from app.db.base_class import Base


class BseClientCode(Base):
    __tablename__ = "BseClientCode"

    ClientCode = Column(String)
    MemberCode = Column(String)
    UserId = Column(UUID(as_uuid=True), ForeignKey("User.Id"))
    RegnType = Column(String)
    PrimaryHolderFirstName = Column(String)
    PrimaryHolderMiddleName = Column(String)
    PrimaryHolderLastName = Column(String)
    TaxStatus = Column(String)
    Gender = Column(String)
    PrimaryHolderDobIncorporation = Column(String)
    OccupationCode = Column(Integer)
    HoldingNature = Column(String)
    SecondHolderFirstName = Column(String)
    SecondHolderMiddleName = Column(String)
    SecondHolderLastName = Column(String)
    ThirdHolderFirstName = Column(String)
    ThirdHolderMiddleName = Column(String)
    ThirdHolderLastName = Column(String)
    SecondHolderDOB = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    ThirdHolderDOB = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    GuardianFirstName = Column(String)
    GuardianMiddleName = Column(String)
    GuardianLastName = Column(String)
    GuardianDOB = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    PrimaryHolderPANExempt = Column(String)
    SecondHolderPANExempt = Column(String)
    ThirdHolderPANExempt = Column(String)
    GuardianPANExempt = Column(String)
    PrimaryHolderPAN = Column(String)
    SecondHolderPAN = Column(String)
    ThirdHolderPAN = Column(String)
    GuardianPAN = Column(String)
    PrimaryHolderExemptCategory = Column(String)
    SecondHolderExemptCategory = Column(String)
    ThirdHolderExemptCategory = Column(String)
    GuardianExemptCategory = Column(String)
    ClientType = Column(String)
    PMS = Column(String)
    DefaultDP = Column(String)
    CDSL_DPID = Column(String)
    CDSLCLTID = Column(String)
    CMBP_Id = Column(Integer)
    NSDLDPID = Column(String)
    NSDLCLTID = Column(String)
    AccountTypeOne = Column(String)
    AccountNoOne = Column(String)
    MICRNoOne = Column(String)
    IFSCCodeOne = Column(String)
    # DefaultBankFlagOne = Column(String)
    # AccountTypeTwo = Column(String)
    # AccountNoTwo = Column(String)
    # MICRNoTwo = Column(String)
    # IFSCCodeTwo = Column(String)
    # DefaultBankFlagTwo = Column(String)
    # AccountTypeThree = Column(String)
    # AccountNoThree = Column(String)
    # MICRNoThree = Column(String)
    # IFSCCodeThree = Column(String)
    # DefaultBankFlagThree = Column(String)
    # AccountTypeFour = Column(String)
    # AccountNoFour = Column(String)
    # MICRNoFour = Column(String)
    # IFSCCodeFour = Column(String)
    # DefaultBankFlagFour = Column(String)
    # AccountTypeFive = Column(String)
    # AccountNoFive = Column(String)
    # MICRNoFive = Column(String
    # IFSCCodeFive = Column(String)
    # DefaultBankFlagFive = Column(String)
    ChequeName = Column(String)
    DivPayMode = Column(String)
    AddressOne = Column(String)
    AddressTwo = Column(String)
    AddressThree = Column(String)
    City = Column(String)
    State = Column(String)
    PinCode = Column(String)
    Country = Column(String)
    ResidentialPhone = Column(String)
    ResidentialFax = Column(String)
    OfficePhone = Column(String)
    OfficeFax = Column(String)
    Email = Column(String)
    CommunicationMode = Column(String)
    ForeignAddressOne = Column(String)
    ForeignAddressTwo = Column(String)
    ForeignAddressThree = Column(String)
    ForeignAddressCity = Column(String)
    ForeignAddressPinCode = Column(String)
    ForeignAddressState = Column(String)
    ForeignAddressCountry = Column(String)
    ForeignAddressResidentialPhone = Column(String)
    ForeignAddressFax = Column(String)
    ForeignAddressOfficePhone = Column(String)
    ForeignAddressOfficeFax = Column(String)
    IndianMobileNo = Column(String)
    # NomineeOneName = Column(String)
    # NomineeOneRelationship = Column(String)
    # NomineeOneApplicablePercent = Column(Float)
    # NomineeOneMinorFlag = Column(String)
    # NomineeOneDOB = Column(DateTime)
    # NomineeOneGuardian = Column(String)
    # NomineeTwoName = Column(String)
    # NomineeTwoRelationship = Column(String)
    # NomineeTwoApplicablePercent = Column(String)
    # NomineeTwoDOB = Column(DateTime)
    # NomineeTwoMinorFlag = Column(String)
    # NomineeTwoGuardian = Column(String)
    # NomineeThreeName = Column(String)
    # NomineeThreeRelationship = Column(String)
    # NomineeThreeApplicablePercent = Column(Float)
    # NomineeThreeDOB = Column(DateTime)
    # NomineeThreeMinorFlag = Column(String)
    # NomineeThreeGuardian = Column(String)
    PrimaryHolderKYCType = Column(String)
    PrimaryHolderCKYCNumber = Column(Integer)
    SecondHolderKYCType = Column(String)
    SecondHolderCKYCNumber = Column(Integer)
    ThirdHolderKYCType = Column(String)
    ThirdHolderCKYCNumber = Column(Integer)
    GuardianKYCType = Column(String)
    GuardianCKYCNumber = Column(Integer)
    PrimaryHolderKRAExemptRefNo = Column(String)
    SecondHolderKRAExemptRefNo = Column(String)
    ThirdHolderKRAExemptRefNo = Column(String)
    GuardianKRAExemptRefNo = Column(String)
    AadhaarUpdated = Column(String)
    MapInId = Column(String)
    PaperLessFlag = Column(String)
    LEINo = Column(String)
    LEIValidity = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    FillerOne = Column(String)
    FillerTwo = Column(String)
    FillerThree = Column(String)
    SignatureUrl = Column(String)
    ChequeUrl = Column(String)
    PanCardUrl = Column(String)
    CreatedOn = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("now()")
    )
    UpdatedOn = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    IsDeleted = Column(Boolean, default=False)
