"""empty message

Revision ID: 7909c0b791b1
Revises: f0566bfc1eee
Create Date: 2022-02-23 14:55:46.488679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7909c0b791b1'
down_revision = 'f0566bfc1eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RrScoreResult', sa.Column('RetirementAge', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RrScoreResult', 'RetirementAge')
    # ### end Alembic commands ###
