"""empty message

Revision ID: e9443fa10fc2
Revises: 0981050f9bc7
Create Date: 2022-02-23 07:41:40.787320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9443fa10fc2'
down_revision = '0981050f9bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AssetClassHierarchy',
    sa.Column('Id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('assetClass', sa.String(), nullable=False),
    sa.Column('assetType', sa.String(), nullable=False),
    sa.Column('CreatedOn', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedOn', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('UniverseTable',
    sa.Column('Id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('mstarid', sa.String(), nullable=False),
    sa.Column('ratingdate', sa.Date(), nullable=False),
    sa.Column('ratingoveraall', sa.Integer(), nullable=False),
    sa.Column('legalname', sa.String(), nullable=False),
    sa.Column('fundame', sa.String(), nullable=False),
    sa.Column('fundlevelcategoryname', sa.String(), nullable=False),
    sa.Column('sharperatio', sa.Float(), nullable=False),
    sa.Column('CreatedOn', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedOn', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('RebalancingBands')
    op.drop_constraint('BseClientAccount_AccountTypeNumber_key', 'BseClientAccount', type_='unique')
    op.drop_constraint('BseClientNominee_NomineeNumber_key', 'BseClientNominee', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('BseClientNominee_NomineeNumber_key', 'BseClientNominee', ['NomineeNumber'])
    op.create_unique_constraint('BseClientAccount_AccountTypeNumber_key', 'BseClientAccount', ['AccountTypeNumber'])
    op.create_table('RebalancingBands',
    sa.Column('Id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('Upper', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('Lower', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('CreatedOn', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('UpdatedOn', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Ref_Id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='RebalancingBands_pkey')
    )
    op.drop_table('UniverseTable')
    op.drop_table('AssetClassHierarchy')
    # ### end Alembic commands ###
