"""empty message

Revision ID: f0566bfc1eee
Revises: e9443fa10fc2
Create Date: 2022-02-23 10:23:25.667824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0566bfc1eee'
down_revision = 'e9443fa10fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RuleAssetAllocation', 'column5')
    op.drop_column('RuleAssetAllocation', 'column6')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RuleAssetAllocation', sa.Column('column6', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('RuleAssetAllocation', sa.Column('column5', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
