"""empty message

Revision ID: f3bedee7a2bf
Revises: 7909c0b791b1
Create Date: 2022-02-25 07:23:23.653749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3bedee7a2bf'
down_revision = '7909c0b791b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CasDataUploadFromPulseLab',
    sa.Column('Id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('UserId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('CasFile', sa.String(), nullable=False),
    sa.Column('Password', sa.Float(), nullable=False),
    sa.Column('CreatedOn', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedOn', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CasDataUploadFromPulseLab')
    # ### end Alembic commands ###
