version: "3.7"

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    restart: always

  app:
    container_name: Fliber
    build:
      context: .
    volumes:
      - ./:/app/
    command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"
    environment:
      - DATABASE_URL=postgresql://fliberadmin@fliber-dev:nIi6TUcBtS@fliber-dev.postgres.database.azure.com:5432/postgres1
      - PYTHONUNBUFFERED
      - DEBUG
      - PORT
    expose:
      - 8080
    ports:
      - 8080:8080
